name: Bug report
description: Report a bug and help improve the plugin
title: '[BUG] '
labels: bug
assignees: shumadrid
body:
  - type: markdown
    attributes:
      value: |
        ## Bug report
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug. Include any relevant details and steps to reproduce.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
    label: Operating system
    description: Which OS are you using?
    options:
      - Windows
      - Linux
      - macOS
      - Android
      - iOS
    validations:
    required: true
  - type: dropdown
    id: installation-method
    attributes:
    label: Installation Method (Linux)
    description: Only necessary on Linux
    options:
      - Flatpak
      - AppImage
      - Snap
      - Other
    validations:
    required: false
  - type: textarea
    attributes:
      label: Environment Information
      description: Environment Information
      value: |
        - **Plugin Version**:
        - **Obsidian Version**:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Attach a video or the vault where the bug occurs. Can be helpful to speed up the bug fix.
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I have tested the bug with the latest version of the plugin
          required: true
        - label: I have checked GitHub for existing bugs
          required: true
