name: Feature request
description: Request a feature and help improve the plugin
title: '[FR] '
labels: enhancement
assignees: shumadrid
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature request. Include any relevant details.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I have tested the absence of the requested feature with the latest version of the plugin
          required: true
        - label: I have checked GitHub for existing Feature Requests
          required: true
