name: 'Main Workflow'
on:
  pull_request:
  push:
permissions:
  contents: read

jobs:
  svelte-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run Svelte-Check
        run: npm run build:compile:svelte

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run build
        run: npm run build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run Prettier
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run CSpell
        run: npm run spellcheck
